#!/usr/bin/env python3
"""gen_api_docs.py — docs/API.md from the FastAPI OpenAPI schema (sator/readme-api-docs:
code is the source, docs are derived). Run after adding or changing an endpoint:

    .venv/bin/python scripts/gen_api_docs.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "api"))
from index import app  # noqa: E402

OUT = ROOT / "docs/API.md"
ROLE_HINT = {"public": "public", "os": "officer (admin where noted)"}


def main() -> None:
    schema = app.openapi()
    lines = ["# API.md — every endpoint (generated by scripts/gen_api_docs.py — do not edit)", "",
             "One Vercel function (`api/index.py`). Public reads fall back to the committed JSON; every `/api/os/*` write is audited and needs an officer session "
             "(Supabase JWT, or `X-Local-Role` off Vercel). Admin-only: board writes, terms/rollover, site-settings, inbox replay.", ""]
    groups: dict[str, list[str]] = {}
    for path, methods in sorted(schema["paths"].items()):
        group = "OS" if path.startswith("/api/os") else "Public"
        for method, op in methods.items():
            summary = (op.get("summary") or op.get("operationId", "")).replace("_", " ")
            desc = (op.get("description") or "").strip().split("\n")[0]
            groups.setdefault(group, []).append(f"| `{method.upper()}` | `{path}` | {summary} | {desc} |")
    for group in ("Public", "OS"):
        lines += [f"## {group} — {ROLE_HINT['os' if group == 'OS' else 'public']}", "", "| Method | Path | Operation | Note |", "|---|---|---|---|", *groups.get(group, []), ""]
    lines += ["## Shapes", "", "Request bodies are the pydantic models in `api/_core/models.py`; the TypeScript twins are generated into "
              "`apps/web/src/lib/api.types.ts` by `scripts/gen_types.py`. Public read responses keep the shape of their `data/*.json` fallback.", ""]
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} ({sum(len(v) for v in groups.values())} endpoints)")


if __name__ == "__main__":
    main()
