#!/usr/bin/env python3
"""gen_types.py — pydantic models (api/_core/models.py) → apps/web/src/lib/api.types.ts.
One source of truth for the API's request shapes. Run after editing models.py:
    .venv/bin/python scripts/gen_types.py
"""
from __future__ import annotations

import sys
import types
import typing
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "api"))
from pydantic import BaseModel  # noqa: E402

from _core import models  # noqa: E402

OUT = ROOT / "apps/web/src/lib/api.types.ts"
PRIM = {str: "string", int: "number", float: "number", bool: "boolean", typing.Any: "unknown"}


def ts(t: object) -> str:
    if t in PRIM:
        return PRIM[t]  # type: ignore[index]
    origin, args = typing.get_origin(t), typing.get_args(t)
    if origin in (types.UnionType, typing.Union):
        return " | ".join("null" if a is type(None) else ts(a) for a in args)
    if origin is list:
        return f"{ts(args[0])}[]"
    if origin is dict:
        return f"Record<{ts(args[0])}, {ts(args[1])}>"
    if origin is typing.Literal:
        return " | ".join(f'"{a}"' for a in args)
    if isinstance(t, type) and issubclass(t, BaseModel):
        return t.__name__
    return "unknown"


def main() -> None:
    lines = ["/** GENERATED by scripts/gen_types.py from api/_core/models.py — do not edit. */", ""]
    for name in dir(models):
        m = getattr(models, name)
        if isinstance(m, type) and issubclass(m, BaseModel) and m is not BaseModel:
            lines.append(f"export type {name} = {{")
            for f, info in m.model_fields.items():
                opt = "?" if not info.is_required() else ""
                lines.append(f"  {f}{opt}: {ts(info.annotation)};")
            lines.append("};\n")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} ({len([ln for ln in lines if ln.startswith('export')])} types)")


if __name__ == "__main__":
    main()
