/** GENERATED by scripts/gen_types.py from api/_core/models.py — do not edit. */

export type BoardProfileIn = {
  client_id?: string | null;
  expected_updated_at?: number | null;
  name: string;
  term?: string | null;
  role_title?: string | null;
  group_label?: string | null;
  email?: string | null;
  photo_path?: string | null;
  bio?: string | null;
  socials?: Record<string, string> | null;
  sort?: number | null;
  active?: boolean | null;
  os_role?: "officer" | "admin" | null;
};

export type ChatIn = {
  message: string;
  page?: string | null;
};

export type DecideIn = {
  decision: "approve" | "request_changes" | "archive" | "in_review";
  note?: string | null;
};

export type EventIn = {
  client_id?: string | null;
  expected_updated_at?: number | null;
  title: string;
  semester?: string | null;
  summary?: string | null;
  date_label?: string | null;
  time_label?: string | null;
  starts_at?: string | null;
  location?: string | null;
  flyer_path?: string | null;
  rsvp_url?: string | null;
  recap_post_id?: string | null;
  status?: "draft" | "published" | "archived" | null;
  when?: "upcoming" | "past" | "cancelled" | null;
  sort?: number | null;
};

export type HandoffIn = {
  client_id?: string | null;
  expected_updated_at?: number | null;
  term?: string | null;
  body_md?: string | null;
  status?: "draft" | "filed" | "acknowledged" | null;
};

export type ImportIn = {
  csv: string;
  dry_run?: boolean;
};

export type LinkIn = {
  client_id?: string | null;
  expected_updated_at?: number | null;
  url: string;
  label?: string | null;
};

export type Material = {
  label: string;
  url: string;
};

export type MemberIn = {
  client_id?: string | null;
  expected_updated_at?: number | null;
  display_name: string;
  discord_handle?: string | null;
  school_email?: string | null;
  status?: "interested" | "member" | "active" | "alumni" | "left" | null;
  joined_term?: string | null;
  last_seen_term?: string | null;
  tags?: string[] | null;
  notes?: string | null;
  source?: "form" | "import" | "manual" | null;
};

export type OnboardingSubmit = {
  name: string;
  email: string;
  major?: string | null;
  class_year?: string | null;
  interests?: string | null;
  discord_handle?: string | null;
};

export type PostIn = {
  client_id?: string | null;
  expected_updated_at?: number | null;
  title: string;
  slug?: string | null;
  dek?: string | null;
  body_md?: string | null;
  cover_path?: string | null;
  tags?: string[] | null;
  status?: "draft" | "review" | "published" | "archived" | null;
};

export type ProjectAuthor = {
  name: string;
  handle?: string | null;
  term?: string | null;
};

export type ProjectIn = {
  client_id?: string | null;
  expected_updated_at?: number | null;
  title: string;
  kind?: "app" | "project" | "research" | "tool" | null;
  summary?: string | null;
  platform?: string[] | null;
  stack?: string[] | null;
  links?: Record<string, string> | null;
  screenshots?: string[] | null;
  benefits_jj?: string | null;
  authors?: ProjectAuthor[] | null;
  featured?: boolean | null;
  display_order?: number | null;
  term?: string | null;
  status?: "submitted" | "in_review" | "changes_requested" | "approved" | "published" | "archived" | null;
  review_notes?: string | null;
};

export type ProjectSubmit = {
  title: string;
  author: string;
  email: string;
  summary: string;
  kind?: "app" | "project" | "research" | "tool";
  platform?: string[] | string | null;
  link?: string | null;
};

export type PruneIn = {
  months?: number;
};

export type ReorderIn = {
  ids: string[];
};

export type ReplayIn = {
  client_ids?: string[] | null;
};

export type ResourceIn = {
  client_id?: string | null;
  expected_updated_at?: number | null;
  group: string;
  title: string;
  url: string;
  description?: string | null;
  sort?: number | null;
  group_sort?: number | null;
  last_checked?: number | null;
  last_status?: number | null;
  dead?: boolean | null;
};

export type SettingIn = {
  value: unknown;
};

export type TermIn = {
  client_id?: string | null;
  expected_updated_at?: number | null;
  id: string;
  label: string;
  starts_on?: string | null;
  ends_on?: string | null;
  is_current?: boolean | null;
};

export type TransitionIn = {
  to: string;
  note?: string | null;
};

export type WorkshopIn = {
  client_id?: string | null;
  expected_updated_at?: number | null;
  title: string;
  series?: string | null;
  session_no?: number | null;
  date?: string | null;
  time?: string | null;
  location?: string | null;
  level?: "intro" | "intermediate" | null;
  description_md?: string | null;
  materials?: Material[] | null;
  recording_url?: string | null;
  status?: "draft" | "published" | "archived" | null;
  sort?: number | null;
};

export type WriteMeta = {
  client_id?: string | null;
  expected_updated_at?: number | null;
};
